apiVersion: v1
kind: Service

metadata:
  name: shopsphere-backend
  namespace: shopsphere

spec:
  type: ClusterIP

  selector:
    app: shopsphere-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

